### ISSUE TITLE
Please develop a nema23/34 version 

### ISSUE THREAD

**Issue by mac7988** [VIPQualityPost/lemon-pepper-stepper#10]
There needs to be an affordable integrated controller in the market to be suitable replacement to Clearpath teknic. 

I am happy to donate if you can make an open source  bldc verison

**Comment by VIPQualityPost** [comment]
Sorry I didn't write back.. I would love to make a larger version, but currently my next plan is for NEMA17.
A similiar project you might find interesting is Funqi Stack which does support NEMA23 I believe, but is a bit more complicated to build: https://community.simplefoc.com/t/the-field-stack-stspin32g4/3032
